apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis.ruby.love
spec:
  group: ruby.love
  scope: Cluster
  names:
    plural: redis
    singular: redis
    kind: Redis
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                cpu:
                  type: string
                memory:
                  type: string
